# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
-   repo: https://github.com/pycqa/isort
    rev: 5.3.2
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
    -   id: black
        pass_filenames: true
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        pass_filenames: true
        # this seems to need to be here in addition to setup.cfg
        exclude: __init__.py
            - flake8-docstrings
